### ISSUE TITLE
the function get asset price keeps returning 0

### ISSUE THREAD

**Issue by Godhanded** [Epic-Byte/Digital-Library-Marketplace#2]
The chain link data feed is working and the price of eth to usd is given to the contract, but when i try to compute is in function assetprice it returns 0, I suspect its the conversion between int and uint. Check the test branch for code: [Link to branch here](https://github.com/Epic-Byte/Digital-Library-Marketplace/tree/test)

**Comment by kingzamzon** [comment]
Conversion between unint and int can cause that also

**Comment by Godhanded** [comment]
it was overflow underflow, can you imagine
